name: CI

# TODO - Integrate the uv tooling
# https://github.com/astral-sh/setup-uv

# - name: Install the latest version of uv
#  uses: astral-sh/setup-uv@v6
#  with:
#    version: "latest"

# ----------

# jobs:
#  test:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: ["3.9", "3.10", "3.11", "3.12"]
#    steps:
#      - uses: actions/checkout@v4
#      - name: Install the latest version of uv and set the python version
#        uses: astral-sh/setup-uv@v6
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Test with python ${{ matrix.python-version }}
#        run: uv run --frozen pytest

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.13"

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pytest regex sqlmodel tqdm aiosqlite aioshutil
        # uses: py-actions/py-dependency-install@v4 - Mutually exclusive to 'run'
        # with:
        #   update-pip: "false"
        #   update-setuptools: "false"
        #   update-wheel: "false"


      - name: Run Test Suites
        run: pytest